# Generated by Django 4.0.5 on 2022-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='content',
            field=models.TextField(max_length=1700),
        ),
        migrations.AlterField(
            model_name='micropost',
            name='image',
            field=models.ImageField(upload_to='micropost-images/'),
        ),
    ]
