# Generated by Django 4.0.6 on 2022-07-19 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microposts', '0003_rename_likes_micropostcomment_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropost',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='micropost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='micropostcomment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='micropost_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
