# Generated by Django 4.0.6 on 2022-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microposts', '0005_remove_micropost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micropostcomment',
            name='upvotes',
        ),
    ]
