# Generated by Django 4.0.5 on 2022-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('categories', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
