# Generated by Django 4.0.5 on 2022-07-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='categories',
        ),
    ]
