# Generated by Django 4.0.5 on 2022-07-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
