# Generated by Django 4.0.5 on 2022-07-01 09:54

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_tag_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('summary', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='article-images/')),
                ('image_credit', models.CharField(blank=True, max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('type', models.CharField(choices=[('Article', 'Article'), ('Story', 'Story'), ('List', 'List'), ('Checklist', 'Checklist'), ('What if...', 'What If...'), ('Questions To Ask', 'Questions To Ask'), ('Myth-buster', 'Myth-buster'), ('Lesson-learned', 'Lesson-learned'), ('What People say', 'What People say')], default='Article', max_length=25)),
                ('featured', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'unique_together': {('author', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.comment')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
