# Generated by Django 4.0.6 on 2022-07-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecomment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='likes',
            new_name='likers',
        ),
    ]
