# Generated by Django 4.0.6 on 2022-07-18 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_rename_likes_articlecomment_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='article_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
