# Generated by Django 4.0.5 on 2022-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='upvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='modified',
        ),
    ]
