# Generated by Django 4.0.5 on 2022-07-07 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_rename_likes_comment_upvotes_remove_comment_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ArticleComment',
        ),
    ]
