# Generated by Django 4.0.6 on 2022-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
