# Generated by Django 4.0.6 on 2022-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_article_likes_remove_articlecomment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='upvotes',
        ),
    ]
