# Generated by Django 4.0.5 on 2022-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='profile/profile-background/'),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/profile-images/'),
        ),
    ]
