# Generated by Django 4.0.5 on 2022-06-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
