# Generated by Django 4.0.5 on 2022-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender'), ('Non-binary', 'Non-binary/non-conforming'), ('No response', 'Prefer not to respond')], default='No response', max_length=25),
        ),
    ]
