# Generated by Django 4.0.5 on 2022-07-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_background_image_account_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='background_image',
        ),
    ]
