# Generated by Django 4.0.5 on 2022-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='accounts/profile-images/'),
        ),
    ]
